# coding: utf-8

# flake8: noqa

"""
    SleepHQ

    SleepHQ is an online platform for CPAP users to view, share and analyse their data to get the best night's sleep possible. Visit https://sleephq.com for more details.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "0.1.0"

# Define package exports
__all__ = [
    "CurrentUserApi",
    "DevicesApi",
    "ImportFilesApi",
    "ImportsApi",
    "JournalsApi",
    "MachineDatesApi",
    "MachinesApi",
    "PatientsApi",
    "TeamsApi",
    "ActiveStorageApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "ApiV1DeviceSerializer",
    "ApiV1DeviceSerializerData",
    "ApiV1DeviceSerializerDataAttributes",
    "ApiV1DeviceSerializerList",
    "ApiV1ImportSerializer",
    "ApiV1ImportSerializerData",
    "ApiV1ImportSerializerDataAttributes",
    "ApiV1ImportSerializerDataRelationships",
    "ApiV1ImportSerializerList",
    "ApiV1ImportsFileSerializer",
    "ApiV1ImportsFileSerializerData",
    "ApiV1ImportsFileSerializerDataAttributes",
    "ApiV1ImportsFileSerializerList",
    "ApiV1JournalSerializer",
    "ApiV1JournalSerializerData",
    "ApiV1JournalSerializerDataAttributes",
    "ApiV1JournalSerializerList",
    "ApiV1MachineDateSerializer",
    "ApiV1MachineDateSerializerData",
    "ApiV1MachineDateSerializerDataAttributes",
    "ApiV1MachineDateSerializerList",
    "ApiV1MachineSerializer",
    "ApiV1MachineSerializerData",
    "ApiV1MachineSerializerDataAttributes",
    "ApiV1MachineSerializerList",
    "ApiV1PatientSerializer",
    "ApiV1PatientSerializerData",
    "ApiV1PatientSerializerDataAttributes",
    "ApiV1PatientSerializerDataRelationships",
    "ApiV1PatientSerializerList",
    "ApiV1TeamSerializer",
    "ApiV1TeamSerializerData",
    "ApiV1TeamSerializerDataAttributes",
    "ApiV1TeamSerializerList",
    "ApiV1UserSerializer",
    "ApiV1UserSerializerData",
    "ApiV1UserSerializerDataAttributes",
    "ApiV1UserSerializerDataRelationships",
    "ApiV1UserSerializerDataRelationshipsTeams",
    "ApiV1UserSerializerDataRelationshipsTeamsDataInner",
    "PostV1ActiveStorageBlobsRequest",
    "PostV1ImportsFilesCalculateContentHashRequest",
    "PostV1ImportsImportIdFilesRequest",
    "PostV1MeRequest",
    "PostV1TeamsTeamIdImportsRequest",
    "PostV1TeamsTeamIdJournalsRequest",
    "PutV1MachineDatesIdRequest",
    "V1MeResponse",
]

# import apis into sdk package
from sleephq.api.current_user_api import CurrentUserApi as CurrentUserApi
from sleephq.api.devices_api import DevicesApi as DevicesApi
from sleephq.api.import_files_api import ImportFilesApi as ImportFilesApi
from sleephq.api.imports_api import ImportsApi as ImportsApi
from sleephq.api.journals_api import JournalsApi as JournalsApi
from sleephq.api.machine_dates_api import MachineDatesApi as MachineDatesApi
from sleephq.api.machines_api import MachinesApi as MachinesApi
from sleephq.api.patients_api import PatientsApi as PatientsApi
from sleephq.api.teams_api import TeamsApi as TeamsApi
from sleephq.api.active_storage_api import ActiveStorageApi as ActiveStorageApi

# import ApiClient
from sleephq.api_response import ApiResponse as ApiResponse
from sleephq.api_client import ApiClient as ApiClient
from sleephq.configuration import Configuration as Configuration
from sleephq.exceptions import OpenApiException as OpenApiException
from sleephq.exceptions import ApiTypeError as ApiTypeError
from sleephq.exceptions import ApiValueError as ApiValueError
from sleephq.exceptions import ApiKeyError as ApiKeyError
from sleephq.exceptions import ApiAttributeError as ApiAttributeError
from sleephq.exceptions import ApiException as ApiException

# import models into sdk package
from sleephq.models.api_v1_device_serializer import ApiV1DeviceSerializer as ApiV1DeviceSerializer
from sleephq.models.api_v1_device_serializer_data import ApiV1DeviceSerializerData as ApiV1DeviceSerializerData
from sleephq.models.api_v1_device_serializer_data_attributes import ApiV1DeviceSerializerDataAttributes as ApiV1DeviceSerializerDataAttributes
from sleephq.models.api_v1_device_serializer_list import ApiV1DeviceSerializerList as ApiV1DeviceSerializerList
from sleephq.models.api_v1_import_serializer import ApiV1ImportSerializer as ApiV1ImportSerializer
from sleephq.models.api_v1_import_serializer_data import ApiV1ImportSerializerData as ApiV1ImportSerializerData
from sleephq.models.api_v1_import_serializer_data_attributes import ApiV1ImportSerializerDataAttributes as ApiV1ImportSerializerDataAttributes
from sleephq.models.api_v1_import_serializer_data_relationships import ApiV1ImportSerializerDataRelationships as ApiV1ImportSerializerDataRelationships
from sleephq.models.api_v1_import_serializer_list import ApiV1ImportSerializerList as ApiV1ImportSerializerList
from sleephq.models.api_v1_imports_file_serializer import ApiV1ImportsFileSerializer as ApiV1ImportsFileSerializer
from sleephq.models.api_v1_imports_file_serializer_data import ApiV1ImportsFileSerializerData as ApiV1ImportsFileSerializerData
from sleephq.models.api_v1_imports_file_serializer_data_attributes import ApiV1ImportsFileSerializerDataAttributes as ApiV1ImportsFileSerializerDataAttributes
from sleephq.models.api_v1_imports_file_serializer_list import ApiV1ImportsFileSerializerList as ApiV1ImportsFileSerializerList
from sleephq.models.api_v1_journal_serializer import ApiV1JournalSerializer as ApiV1JournalSerializer
from sleephq.models.api_v1_journal_serializer_data import ApiV1JournalSerializerData as ApiV1JournalSerializerData
from sleephq.models.api_v1_journal_serializer_data_attributes import ApiV1JournalSerializerDataAttributes as ApiV1JournalSerializerDataAttributes
from sleephq.models.api_v1_journal_serializer_list import ApiV1JournalSerializerList as ApiV1JournalSerializerList
from sleephq.models.api_v1_machine_date_serializer import ApiV1MachineDateSerializer as ApiV1MachineDateSerializer
from sleephq.models.api_v1_machine_date_serializer_data import ApiV1MachineDateSerializerData as ApiV1MachineDateSerializerData
from sleephq.models.api_v1_machine_date_serializer_data_attributes import ApiV1MachineDateSerializerDataAttributes as ApiV1MachineDateSerializerDataAttributes
from sleephq.models.api_v1_machine_date_serializer_list import ApiV1MachineDateSerializerList as ApiV1MachineDateSerializerList
from sleephq.models.api_v1_machine_serializer import ApiV1MachineSerializer as ApiV1MachineSerializer
from sleephq.models.api_v1_machine_serializer_data import ApiV1MachineSerializerData as ApiV1MachineSerializerData
from sleephq.models.api_v1_machine_serializer_data_attributes import ApiV1MachineSerializerDataAttributes as ApiV1MachineSerializerDataAttributes
from sleephq.models.api_v1_machine_serializer_list import ApiV1MachineSerializerList as ApiV1MachineSerializerList
from sleephq.models.api_v1_patient_serializer import ApiV1PatientSerializer as ApiV1PatientSerializer
from sleephq.models.api_v1_patient_serializer_data import ApiV1PatientSerializerData as ApiV1PatientSerializerData
from sleephq.models.api_v1_patient_serializer_data_attributes import ApiV1PatientSerializerDataAttributes as ApiV1PatientSerializerDataAttributes
from sleephq.models.api_v1_patient_serializer_data_relationships import ApiV1PatientSerializerDataRelationships as ApiV1PatientSerializerDataRelationships
from sleephq.models.api_v1_patient_serializer_list import ApiV1PatientSerializerList as ApiV1PatientSerializerList
from sleephq.models.api_v1_team_serializer import ApiV1TeamSerializer as ApiV1TeamSerializer
from sleephq.models.api_v1_team_serializer_data import ApiV1TeamSerializerData as ApiV1TeamSerializerData
from sleephq.models.api_v1_team_serializer_data_attributes import ApiV1TeamSerializerDataAttributes as ApiV1TeamSerializerDataAttributes
from sleephq.models.api_v1_team_serializer_list import ApiV1TeamSerializerList as ApiV1TeamSerializerList
from sleephq.models.api_v1_user_serializer import ApiV1UserSerializer as ApiV1UserSerializer
from sleephq.models.api_v1_user_serializer_data import ApiV1UserSerializerData as ApiV1UserSerializerData
from sleephq.models.api_v1_user_serializer_data_attributes import ApiV1UserSerializerDataAttributes as ApiV1UserSerializerDataAttributes
from sleephq.models.api_v1_user_serializer_data_relationships import ApiV1UserSerializerDataRelationships as ApiV1UserSerializerDataRelationships
from sleephq.models.api_v1_user_serializer_data_relationships_teams import ApiV1UserSerializerDataRelationshipsTeams as ApiV1UserSerializerDataRelationshipsTeams
from sleephq.models.api_v1_user_serializer_data_relationships_teams_data_inner import ApiV1UserSerializerDataRelationshipsTeamsDataInner as ApiV1UserSerializerDataRelationshipsTeamsDataInner
from sleephq.models.post_v1_active_storage_blobs_request import PostV1ActiveStorageBlobsRequest as PostV1ActiveStorageBlobsRequest
from sleephq.models.post_v1_imports_files_calculate_content_hash_request import PostV1ImportsFilesCalculateContentHashRequest as PostV1ImportsFilesCalculateContentHashRequest
from sleephq.models.post_v1_imports_import_id_files_request import PostV1ImportsImportIdFilesRequest as PostV1ImportsImportIdFilesRequest
from sleephq.models.post_v1_me_request import PostV1MeRequest as PostV1MeRequest
from sleephq.models.post_v1_teams_team_id_imports_request import PostV1TeamsTeamIdImportsRequest as PostV1TeamsTeamIdImportsRequest
from sleephq.models.post_v1_teams_team_id_journals_request import PostV1TeamsTeamIdJournalsRequest as PostV1TeamsTeamIdJournalsRequest
from sleephq.models.put_v1_machine_dates_id_request import PutV1MachineDatesIdRequest as PutV1MachineDatesIdRequest
from sleephq.models.v1_me_response import V1MeResponse as V1MeResponse


# Hand-written auth helpers (injected by generate.sh)
from sleephq.auth import Client as Client
from sleephq.auth import TokenResponse as TokenResponse
from sleephq.auth import get_token as get_token

__all__ += ["Client", "TokenResponse", "get_token"]
