# coding: utf-8

"""
    SleepHQ

    SleepHQ is an online platform for CPAP users to view, share and analyse their data to get the best night's sleep possible. Visit https://sleephq.com for more details.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class ApiV1ImportsFileSerializerDataAttributes(BaseModel):
    """
    ApiV1ImportsFileSerializerDataAttributes
    """ # noqa: E501
    id: Optional[StrictInt] = None
    added_by_id: Optional[StrictInt] = None
    added_by_type: Optional[StrictStr] = None
    content_hash: Optional[StrictStr] = None
    team_id: Optional[StrictInt] = None
    name: Optional[StrictStr] = None
    path: Optional[StrictStr] = None
    size: Optional[StrictInt] = None
    fingerprint_base64: Optional[StrictStr] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    download_url: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["id", "added_by_id", "added_by_type", "content_hash", "team_id", "name", "path", "size", "fingerprint_base64", "created_at", "updated_at", "download_url"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ApiV1ImportsFileSerializerDataAttributes from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ApiV1ImportsFileSerializerDataAttributes from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "added_by_id": obj.get("added_by_id"),
            "added_by_type": obj.get("added_by_type"),
            "content_hash": obj.get("content_hash"),
            "team_id": obj.get("team_id"),
            "name": obj.get("name"),
            "path": obj.get("path"),
            "size": obj.get("size"),
            "fingerprint_base64": obj.get("fingerprint_base64"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at"),
            "download_url": obj.get("download_url")
        })
        return _obj


