# coding: utf-8

"""
    SleepHQ

    SleepHQ is an online platform for CPAP users to view, share and analyse their data to get the best night's sleep possible. Visit https://sleephq.com for more details.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date, datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class ApiV1JournalSerializerDataAttributes(BaseModel):
    """
    ApiV1JournalSerializerDataAttributes
    """ # noqa: E501
    id: Optional[StrictInt] = None
    team_id: Optional[StrictInt] = None
    var_date: Optional[date] = Field(default=None, alias="date")
    step_count: Optional[StrictInt] = None
    weight_grams: Optional[StrictInt] = None
    feeling_score: Optional[StrictInt] = None
    sleep_stages: Optional[StrictStr] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    notes: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["id", "team_id", "date", "step_count", "weight_grams", "feeling_score", "sleep_stages", "created_at", "updated_at", "notes"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ApiV1JournalSerializerDataAttributes from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ApiV1JournalSerializerDataAttributes from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "team_id": obj.get("team_id"),
            "date": obj.get("date"),
            "step_count": obj.get("step_count"),
            "weight_grams": obj.get("weight_grams"),
            "feeling_score": obj.get("feeling_score"),
            "sleep_stages": obj.get("sleep_stages"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at"),
            "notes": obj.get("notes")
        })
        return _obj


