# coding: utf-8

"""
    SleepHQ

    SleepHQ is an online platform for CPAP users to view, share and analyse their data to get the best night's sleep possible. Visit https://sleephq.com for more details.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date, datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class ApiV1MachineDateSerializerDataAttributes(BaseModel):
    """
    ApiV1MachineDateSerializerDataAttributes
    """ # noqa: E501
    id: Optional[StrictInt] = None
    usage: Optional[StrictInt] = None
    machine_id: Optional[StrictInt] = None
    var_date: Optional[date] = Field(default=None, alias="date")
    time_offset: Optional[StrictInt] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    large_leak: Optional[StrictInt] = None
    ahi_summary: Optional[Dict[str, Any]] = None
    pressure_summary: Optional[Dict[str, Any]] = None
    leak_rate_summary: Optional[Dict[str, Any]] = None
    flow_limit_summary: Optional[Dict[str, Any]] = None
    resp_rate_summary: Optional[Dict[str, Any]] = None
    epap_summary: Optional[Dict[str, Any]] = None
    machine_settings: Optional[Dict[str, Any]] = None
    pulse_rate_summary: Optional[Dict[str, Any]] = None
    spo2_summary: Optional[Dict[str, Any]] = None
    movement_summary: Optional[Dict[str, Any]] = None
    __properties: ClassVar[List[str]] = ["id", "usage", "machine_id", "date", "time_offset", "created_at", "updated_at", "large_leak", "ahi_summary", "pressure_summary", "leak_rate_summary", "flow_limit_summary", "resp_rate_summary", "epap_summary", "machine_settings", "pulse_rate_summary", "spo2_summary", "movement_summary"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ApiV1MachineDateSerializerDataAttributes from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ApiV1MachineDateSerializerDataAttributes from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "usage": obj.get("usage"),
            "machine_id": obj.get("machine_id"),
            "date": obj.get("date"),
            "time_offset": obj.get("time_offset"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at"),
            "large_leak": obj.get("large_leak"),
            "ahi_summary": obj.get("ahi_summary"),
            "pressure_summary": obj.get("pressure_summary"),
            "leak_rate_summary": obj.get("leak_rate_summary"),
            "flow_limit_summary": obj.get("flow_limit_summary"),
            "resp_rate_summary": obj.get("resp_rate_summary"),
            "epap_summary": obj.get("epap_summary"),
            "machine_settings": obj.get("machine_settings"),
            "pulse_rate_summary": obj.get("pulse_rate_summary"),
            "spo2_summary": obj.get("spo2_summary"),
            "movement_summary": obj.get("movement_summary")
        })
        return _obj


