# coding: utf-8

"""
    SleepHQ

    SleepHQ is an online platform for CPAP users to view, share and analyse their data to get the best night's sleep possible. Visit https://sleephq.com for more details.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class PostV1TeamsTeamIdJournalsRequest(BaseModel):
    """
    PostV1TeamsTeamIdJournalsRequest
    """ # noqa: E501
    var_date: Optional[date] = Field(default=None, description="Date", alias="date")
    step_count: Optional[StrictStr] = Field(default=None, description="Step Count")
    weight_grams: Optional[StrictInt] = Field(default=None, description="Weight (Grams)")
    feeling_score: Optional[StrictStr] = Field(default=None, description="Feeling Score")
    active_energy_joules: Optional[StrictInt] = Field(default=None, description="Active Energy (Joules)")
    notes: Optional[StrictStr] = Field(default=None, description="Notes")
    sleep_stages: Optional[StrictStr] = Field(default=None, description="Sleep Stages")
    __properties: ClassVar[List[str]] = ["date", "step_count", "weight_grams", "feeling_score", "active_energy_joules", "notes", "sleep_stages"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PostV1TeamsTeamIdJournalsRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PostV1TeamsTeamIdJournalsRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "date": obj.get("date"),
            "step_count": obj.get("step_count"),
            "weight_grams": obj.get("weight_grams"),
            "feeling_score": obj.get("feeling_score"),
            "active_energy_joules": obj.get("active_energy_joules"),
            "notes": obj.get("notes"),
            "sleep_stages": obj.get("sleep_stages")
        })
        return _obj


