# coding: utf-8

"""
    SleepHQ

    SleepHQ is an online platform for CPAP users to view, share and analyse their data to get the best night's sleep possible. Visit https://sleephq.com for more details.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sleephq.models.api_v1_imports_file_serializer_data import ApiV1ImportsFileSerializerData

class TestApiV1ImportsFileSerializerData(unittest.TestCase):
    """ApiV1ImportsFileSerializerData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV1ImportsFileSerializerData:
        """Test ApiV1ImportsFileSerializerData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV1ImportsFileSerializerData`
        """
        model = ApiV1ImportsFileSerializerData()
        if include_optional:
            return ApiV1ImportsFileSerializerData(
                id = '',
                type = '',
                attributes = sleephq.models.api_v1_imports_file_serializer_data_attributes.Api_V1_Imports_FileSerializer_data_attributes(
                    id = 56, 
                    added_by_id = 56, 
                    added_by_type = '', 
                    content_hash = '', 
                    team_id = 56, 
                    name = '', 
                    path = '', 
                    size = 56, 
                    fingerprint_base64 = '', 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    download_url = '', ),
                relationships = None
            )
        else:
            return ApiV1ImportsFileSerializerData(
        )
        """

    def testApiV1ImportsFileSerializerData(self):
        """Test ApiV1ImportsFileSerializerData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
