# coding: utf-8

"""
    SleepHQ

    SleepHQ is an online platform for CPAP users to view, share and analyse their data to get the best night's sleep possible. Visit https://sleephq.com for more details.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sleephq.models.api_v1_team_serializer_data_attributes import ApiV1TeamSerializerDataAttributes

class TestApiV1TeamSerializerDataAttributes(unittest.TestCase):
    """ApiV1TeamSerializerDataAttributes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV1TeamSerializerDataAttributes:
        """Test ApiV1TeamSerializerDataAttributes
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV1TeamSerializerDataAttributes`
        """
        model = ApiV1TeamSerializerDataAttributes()
        if include_optional:
            return ApiV1TeamSerializerDataAttributes(
                id = 56,
                name = '',
                owner_id = 56,
                time_zone = '',
                locale = '',
                energy_unit = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                teams_type = ''
            )
        else:
            return ApiV1TeamSerializerDataAttributes(
        )
        """

    def testApiV1TeamSerializerDataAttributes(self):
        """Test ApiV1TeamSerializerDataAttributes"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
