# coding: utf-8

"""
    SleepHQ

    SleepHQ is an online platform for CPAP users to view, share and analyse their data to get the best night's sleep possible. Visit https://sleephq.com for more details.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sleephq.models.post_v1_imports_import_id_files_request import PostV1ImportsImportIdFilesRequest

class TestPostV1ImportsImportIdFilesRequest(unittest.TestCase):
    """PostV1ImportsImportIdFilesRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostV1ImportsImportIdFilesRequest:
        """Test PostV1ImportsImportIdFilesRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostV1ImportsImportIdFilesRequest`
        """
        model = PostV1ImportsImportIdFilesRequest()
        if include_optional:
            return PostV1ImportsImportIdFilesRequest(
                name = '',
                path = '',
                file = bytes(b'blah'),
                content_hash = ''
            )
        else:
            return PostV1ImportsImportIdFilesRequest(
                name = '',
                path = '',
                content_hash = '',
        )
        """

    def testPostV1ImportsImportIdFilesRequest(self):
        """Test PostV1ImportsImportIdFilesRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
