# coding: utf-8

"""
    SleepHQ

    SleepHQ is an online platform for CPAP users to view, share and analyse their data to get the best night's sleep possible. Visit https://sleephq.com for more details.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sleephq.models.api_v1_machine_serializer_data_attributes import ApiV1MachineSerializerDataAttributes

class TestApiV1MachineSerializerDataAttributes(unittest.TestCase):
    """ApiV1MachineSerializerDataAttributes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV1MachineSerializerDataAttributes:
        """Test ApiV1MachineSerializerDataAttributes
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV1MachineSerializerDataAttributes`
        """
        model = ApiV1MachineSerializerDataAttributes()
        if include_optional:
            return ApiV1MachineSerializerDataAttributes(
                id = 56,
                team_id = 56,
                model = '',
                brand = '',
                serial_number = '',
                name = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return ApiV1MachineSerializerDataAttributes(
        )
        """

    def testApiV1MachineSerializerDataAttributes(self):
        """Test ApiV1MachineSerializerDataAttributes"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
