# coding: utf-8

"""
    SleepHQ

    SleepHQ is an online platform for CPAP users to view, share and analyse their data to get the best night's sleep possible. Visit https://sleephq.com for more details.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sleephq.models.post_v1_teams_team_id_imports_request import PostV1TeamsTeamIdImportsRequest

class TestPostV1TeamsTeamIdImportsRequest(unittest.TestCase):
    """PostV1TeamsTeamIdImportsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostV1TeamsTeamIdImportsRequest:
        """Test PostV1TeamsTeamIdImportsRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostV1TeamsTeamIdImportsRequest`
        """
        model = PostV1TeamsTeamIdImportsRequest()
        if include_optional:
            return PostV1TeamsTeamIdImportsRequest(
                programatic = True,
                device_id = 56,
                name = ''
            )
        else:
            return PostV1TeamsTeamIdImportsRequest(
        )
        """

    def testPostV1TeamsTeamIdImportsRequest(self):
        """Test PostV1TeamsTeamIdImportsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
