# coding: utf-8

"""
    SleepHQ

    SleepHQ is an online platform for CPAP users to view, share and analyse their data to get the best night's sleep possible. Visit https://sleephq.com for more details.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sleephq.api.machine_dates_api import MachineDatesApi


class TestMachineDatesApi(unittest.TestCase):
    """MachineDatesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MachineDatesApi()

    def tearDown(self) -> None:
        pass

    def test_get_v1_machine_dates_id(self) -> None:
        """Test case for get_v1_machine_dates_id

        """
        pass

    def test_get_v1_machines_machine_id_machine_dates(self) -> None:
        """Test case for get_v1_machines_machine_id_machine_dates

        """
        pass

    def test_get_v1_machines_machine_id_machine_dates_date(self) -> None:
        """Test case for get_v1_machines_machine_id_machine_dates_date

        """
        pass

    def test_put_v1_machine_dates_id(self) -> None:
        """Test case for put_v1_machine_dates_id

        """
        pass


if __name__ == '__main__':
    unittest.main()
