# coding: utf-8

"""
    SleepHQ

    SleepHQ is an online platform for CPAP users to view, share and analyse their data to get the best night's sleep possible. Visit https://sleephq.com for more details.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sleephq.models.api_v1_device_serializer_data import ApiV1DeviceSerializerData

class TestApiV1DeviceSerializerData(unittest.TestCase):
    """ApiV1DeviceSerializerData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV1DeviceSerializerData:
        """Test ApiV1DeviceSerializerData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV1DeviceSerializerData`
        """
        model = ApiV1DeviceSerializerData()
        if include_optional:
            return ApiV1DeviceSerializerData(
                id = '',
                type = '',
                attributes = sleephq.models.api_v1_device_serializer_data_attributes.Api_V1_DeviceSerializer_data_attributes(
                    id = 56, 
                    name = '', 
                    brand = '', 
                    device_type = '', ),
                relationships = None
            )
        else:
            return ApiV1DeviceSerializerData(
        )
        """

    def testApiV1DeviceSerializerData(self):
        """Test ApiV1DeviceSerializerData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
