# coding: utf-8

"""
    SleepHQ

    SleepHQ is an online platform for CPAP users to view, share and analyse their data to get the best night's sleep possible. Visit https://sleephq.com for more details.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sleephq.models.post_v1_teams_team_id_journals_request import PostV1TeamsTeamIdJournalsRequest

class TestPostV1TeamsTeamIdJournalsRequest(unittest.TestCase):
    """PostV1TeamsTeamIdJournalsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostV1TeamsTeamIdJournalsRequest:
        """Test PostV1TeamsTeamIdJournalsRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostV1TeamsTeamIdJournalsRequest`
        """
        model = PostV1TeamsTeamIdJournalsRequest()
        if include_optional:
            return PostV1TeamsTeamIdJournalsRequest(
                var_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                step_count = '',
                weight_grams = 56,
                feeling_score = '',
                active_energy_joules = 56,
                notes = '',
                sleep_stages = ''
            )
        else:
            return PostV1TeamsTeamIdJournalsRequest(
        )
        """

    def testPostV1TeamsTeamIdJournalsRequest(self):
        """Test PostV1TeamsTeamIdJournalsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
