# coding: utf-8

"""
    SleepHQ

    SleepHQ is an online platform for CPAP users to view, share and analyse their data to get the best night's sleep possible. Visit https://sleephq.com for more details.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sleephq.models.post_v1_active_storage_blobs_request import PostV1ActiveStorageBlobsRequest

class TestPostV1ActiveStorageBlobsRequest(unittest.TestCase):
    """PostV1ActiveStorageBlobsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostV1ActiveStorageBlobsRequest:
        """Test PostV1ActiveStorageBlobsRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostV1ActiveStorageBlobsRequest`
        """
        model = PostV1ActiveStorageBlobsRequest()
        if include_optional:
            return PostV1ActiveStorageBlobsRequest(
                blob_filename = '',
                blob_content_type = '',
                blob_byte_size = 56,
                blob_checksum = ''
            )
        else:
            return PostV1ActiveStorageBlobsRequest(
                blob_filename = '',
                blob_content_type = '',
                blob_byte_size = 56,
                blob_checksum = '',
        )
        """

    def testPostV1ActiveStorageBlobsRequest(self):
        """Test PostV1ActiveStorageBlobsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
