# coding: utf-8

"""
    SleepHQ

    SleepHQ is an online platform for CPAP users to view, share and analyse their data to get the best night's sleep possible. Visit https://sleephq.com for more details.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sleephq.models.api_v1_imports_file_serializer_data_attributes import ApiV1ImportsFileSerializerDataAttributes

class TestApiV1ImportsFileSerializerDataAttributes(unittest.TestCase):
    """ApiV1ImportsFileSerializerDataAttributes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV1ImportsFileSerializerDataAttributes:
        """Test ApiV1ImportsFileSerializerDataAttributes
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV1ImportsFileSerializerDataAttributes`
        """
        model = ApiV1ImportsFileSerializerDataAttributes()
        if include_optional:
            return ApiV1ImportsFileSerializerDataAttributes(
                id = 56,
                added_by_id = 56,
                added_by_type = '',
                content_hash = '',
                team_id = 56,
                name = '',
                path = '',
                size = 56,
                fingerprint_base64 = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                download_url = ''
            )
        else:
            return ApiV1ImportsFileSerializerDataAttributes(
        )
        """

    def testApiV1ImportsFileSerializerDataAttributes(self):
        """Test ApiV1ImportsFileSerializerDataAttributes"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
