# coding: utf-8

"""
    SleepHQ

    SleepHQ is an online platform for CPAP users to view, share and analyse their data to get the best night's sleep possible. Visit https://sleephq.com for more details.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sleephq.models.post_v1_imports_files_calculate_content_hash_request import PostV1ImportsFilesCalculateContentHashRequest

class TestPostV1ImportsFilesCalculateContentHashRequest(unittest.TestCase):
    """PostV1ImportsFilesCalculateContentHashRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostV1ImportsFilesCalculateContentHashRequest:
        """Test PostV1ImportsFilesCalculateContentHashRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostV1ImportsFilesCalculateContentHashRequest`
        """
        model = PostV1ImportsFilesCalculateContentHashRequest()
        if include_optional:
            return PostV1ImportsFilesCalculateContentHashRequest(
                name = '',
                file = bytes(b'blah')
            )
        else:
            return PostV1ImportsFilesCalculateContentHashRequest(
                name = '',
                file = bytes(b'blah'),
        )
        """

    def testPostV1ImportsFilesCalculateContentHashRequest(self):
        """Test PostV1ImportsFilesCalculateContentHashRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
