# coding: utf-8

"""
    SleepHQ

    SleepHQ is an online platform for CPAP users to view, share and analyse their data to get the best night's sleep possible. Visit https://sleephq.com for more details.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sleephq.models.api_v1_user_serializer_data import ApiV1UserSerializerData

class TestApiV1UserSerializerData(unittest.TestCase):
    """ApiV1UserSerializerData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV1UserSerializerData:
        """Test ApiV1UserSerializerData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV1UserSerializerData`
        """
        model = ApiV1UserSerializerData()
        if include_optional:
            return ApiV1UserSerializerData(
                id = '',
                type = '',
                attributes = sleephq.models.api_v1_user_serializer_data_attributes.Api_V1_UserSerializer_data_attributes(
                    id = 56, 
                    email = '', 
                    name = '', 
                    first_name = '', 
                    last_name = '', 
                    time_zone = '', 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                relationships = sleephq.models.api_v1_user_serializer_data_relationships.Api_V1_UserSerializer_data_relationships(
                    teams = sleephq.models.api_v1_user_serializer_data_relationships_teams.Api_V1_UserSerializer_data_relationships_teams(
                        data = [
                            sleephq.models.api_v1_user_serializer_data_relationships_teams_data_inner.Api_V1_UserSerializer_data_relationships_teams_data_inner(
                                id = '', 
                                type = '', )
                            ], ), 
                    memberships = sleephq.models.api_v1_user_serializer_data_relationships_teams.Api_V1_UserSerializer_data_relationships_teams(), )
            )
        else:
            return ApiV1UserSerializerData(
        )
        """

    def testApiV1UserSerializerData(self):
        """Test ApiV1UserSerializerData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
