# coding: utf-8

"""
    SleepHQ

    SleepHQ is an online platform for CPAP users to view, share and analyse their data to get the best night's sleep possible. Visit https://sleephq.com for more details.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sleephq.models.api_v1_journal_serializer_data_attributes import ApiV1JournalSerializerDataAttributes

class TestApiV1JournalSerializerDataAttributes(unittest.TestCase):
    """ApiV1JournalSerializerDataAttributes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV1JournalSerializerDataAttributes:
        """Test ApiV1JournalSerializerDataAttributes
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV1JournalSerializerDataAttributes`
        """
        model = ApiV1JournalSerializerDataAttributes()
        if include_optional:
            return ApiV1JournalSerializerDataAttributes(
                id = 56,
                team_id = 56,
                var_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                step_count = 56,
                weight_grams = 56,
                feeling_score = 56,
                sleep_stages = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                notes = ''
            )
        else:
            return ApiV1JournalSerializerDataAttributes(
        )
        """

    def testApiV1JournalSerializerDataAttributes(self):
        """Test ApiV1JournalSerializerDataAttributes"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
