# coding: utf-8

"""
    SleepHQ

    SleepHQ is an online platform for CPAP users to view, share and analyse their data to get the best night's sleep possible. Visit https://sleephq.com for more details.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sleephq.models.api_v1_machine_serializer import ApiV1MachineSerializer

class TestApiV1MachineSerializer(unittest.TestCase):
    """ApiV1MachineSerializer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV1MachineSerializer:
        """Test ApiV1MachineSerializer
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV1MachineSerializer`
        """
        model = ApiV1MachineSerializer()
        if include_optional:
            return ApiV1MachineSerializer(
                data = {"id":1,"type":"machine","attributes":{"id":2182077251,"team_id":2762207076,"model":"quaerat","brand":"enim","serial_number":"qui","name":"animi","created_at":"2026-01-14 07:50:46 UTC","updated_at":"2026-01-14 07:50:46 UTC"},"relationships":{}}
            )
        else:
            return ApiV1MachineSerializer(
        )
        """

    def testApiV1MachineSerializer(self):
        """Test ApiV1MachineSerializer"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
