# coding: utf-8

"""
    SleepHQ

    SleepHQ is an online platform for CPAP users to view, share and analyse their data to get the best night's sleep possible. Visit https://sleephq.com for more details.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sleephq.models.api_v1_journal_serializer_list import ApiV1JournalSerializerList

class TestApiV1JournalSerializerList(unittest.TestCase):
    """ApiV1JournalSerializerList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV1JournalSerializerList:
        """Test ApiV1JournalSerializerList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV1JournalSerializerList`
        """
        model = ApiV1JournalSerializerList()
        if include_optional:
            return ApiV1JournalSerializerList(
                data = [
                    {"id":1,"type":"journal","attributes":{"id":1171770984,"team_id":8786159917,"date":"2026-01-14","step_count":9752404026,"weight_grams":8656783073,"feeling_score":9777778271,"sleep_stages":"Autem recusandae dignissimos. Ut autem ut. Sed praesentium voluptas.","created_at":"2026-01-14 07:50:46 UTC","updated_at":"2026-01-14 07:50:46 UTC","notes":"adipisci"},"relationships":{}}
                    ]
            )
        else:
            return ApiV1JournalSerializerList(
        )
        """

    def testApiV1JournalSerializerList(self):
        """Test ApiV1JournalSerializerList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
