# coding: utf-8

"""
    SleepHQ

    SleepHQ is an online platform for CPAP users to view, share and analyse their data to get the best night's sleep possible. Visit https://sleephq.com for more details.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sleephq.models.api_v1_import_serializer_data_attributes import ApiV1ImportSerializerDataAttributes

class TestApiV1ImportSerializerDataAttributes(unittest.TestCase):
    """ApiV1ImportSerializerDataAttributes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV1ImportSerializerDataAttributes:
        """Test ApiV1ImportSerializerDataAttributes
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV1ImportSerializerDataAttributes`
        """
        model = ApiV1ImportSerializerDataAttributes()
        if include_optional:
            return ApiV1ImportSerializerDataAttributes(
                id = 56,
                team_id = 56,
                name = '',
                status = '',
                file_size = 56,
                progress = 56,
                machine_id = 56,
                device_id = 56,
                programatic = True,
                failed_reason = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return ApiV1ImportSerializerDataAttributes(
        )
        """

    def testApiV1ImportSerializerDataAttributes(self):
        """Test ApiV1ImportSerializerDataAttributes"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
