# coding: utf-8

"""
    SleepHQ

    SleepHQ is an online platform for CPAP users to view, share and analyse their data to get the best night's sleep possible. Visit https://sleephq.com for more details.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sleephq.models.post_v1_me_request import PostV1MeRequest

class TestPostV1MeRequest(unittest.TestCase):
    """PostV1MeRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostV1MeRequest:
        """Test PostV1MeRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostV1MeRequest`
        """
        model = PostV1MeRequest()
        if include_optional:
            return PostV1MeRequest(
                first_name = '',
                last_name = '',
                email = ''
            )
        else:
            return PostV1MeRequest(
        )
        """

    def testPostV1MeRequest(self):
        """Test PostV1MeRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
