# coding: utf-8

"""
    SleepHQ

    SleepHQ is an online platform for CPAP users to view, share and analyse their data to get the best night's sleep possible. Visit https://sleephq.com for more details.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sleephq.models.api_v1_user_serializer import ApiV1UserSerializer

class TestApiV1UserSerializer(unittest.TestCase):
    """ApiV1UserSerializer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV1UserSerializer:
        """Test ApiV1UserSerializer
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV1UserSerializer`
        """
        model = ApiV1UserSerializer()
        if include_optional:
            return ApiV1UserSerializer(
                data = {"id":1,"type":"user","attributes":{"id":1628261873,"email":"distinctio","name":"ratione","first_name":"molestias","last_name":"reiciendis","time_zone":"voluptatem","created_at":"2026-01-14 07:50:46 UTC","updated_at":"2026-01-14 07:50:46 UTC"},"relationships":{"teams":{"data":[{"id":1,"type":"teams"}]},"memberships":{"data":[{"id":1,"type":"memberships"}]}}}
            )
        else:
            return ApiV1UserSerializer(
        )
        """

    def testApiV1UserSerializer(self):
        """Test ApiV1UserSerializer"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
