# coding: utf-8

"""
    SleepHQ

    SleepHQ is an online platform for CPAP users to view, share and analyse their data to get the best night's sleep possible. Visit https://sleephq.com for more details.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sleephq.models.api_v1_patient_serializer_list import ApiV1PatientSerializerList

class TestApiV1PatientSerializerList(unittest.TestCase):
    """ApiV1PatientSerializerList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV1PatientSerializerList:
        """Test ApiV1PatientSerializerList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV1PatientSerializerList`
        """
        model = ApiV1PatientSerializerList()
        if include_optional:
            return ApiV1PatientSerializerList(
                data = [
                    {"id":1,"type":"patient","attributes":{"id":6611958336,"team_id":4975976738,"name":"amet","created_at":"2026-01-14 07:50:46 UTC","updated_at":"2026-01-14 07:50:46 UTC"},"relationships":{"machines":{"data":[{"id":1,"type":"machines"}]}}}
                    ]
            )
        else:
            return ApiV1PatientSerializerList(
        )
        """

    def testApiV1PatientSerializerList(self):
        """Test ApiV1PatientSerializerList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
