# coding: utf-8

"""
    SleepHQ

    SleepHQ is an online platform for CPAP users to view, share and analyse their data to get the best night's sleep possible. Visit https://sleephq.com for more details.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sleephq.models.api_v1_machine_date_serializer_data import ApiV1MachineDateSerializerData

class TestApiV1MachineDateSerializerData(unittest.TestCase):
    """ApiV1MachineDateSerializerData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV1MachineDateSerializerData:
        """Test ApiV1MachineDateSerializerData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV1MachineDateSerializerData`
        """
        model = ApiV1MachineDateSerializerData()
        if include_optional:
            return ApiV1MachineDateSerializerData(
                id = '',
                type = '',
                attributes = sleephq.models.api_v1_machine_date_serializer_data_attributes.Api_V1_MachineDateSerializer_data_attributes(
                    id = 56, 
                    usage = 56, 
                    machine_id = 56, 
                    date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    time_offset = 56, 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    large_leak = 56, 
                    ahi_summary = sleephq.models.ahi_summary.ahi_summary(), 
                    pressure_summary = sleephq.models.pressure_summary.pressure_summary(), 
                    leak_rate_summary = sleephq.models.leak_rate_summary.leak_rate_summary(), 
                    flow_limit_summary = sleephq.models.flow_limit_summary.flow_limit_summary(), 
                    resp_rate_summary = sleephq.models.resp_rate_summary.resp_rate_summary(), 
                    epap_summary = sleephq.models.epap_summary.epap_summary(), 
                    machine_settings = sleephq.models.machine_settings.machine_settings(), 
                    pulse_rate_summary = sleephq.models.pulse_rate_summary.pulse_rate_summary(), 
                    spo2_summary = sleephq.models.spo2_summary.spo2_summary(), 
                    movement_summary = sleephq.models.movement_summary.movement_summary(), ),
                relationships = None
            )
        else:
            return ApiV1MachineDateSerializerData(
        )
        """

    def testApiV1MachineDateSerializerData(self):
        """Test ApiV1MachineDateSerializerData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
