# coding: utf-8

"""
    SleepHQ

    SleepHQ is an online platform for CPAP users to view, share and analyse their data to get the best night's sleep possible. Visit https://sleephq.com for more details.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sleephq.models.put_v1_machine_dates_id_request import PutV1MachineDatesIdRequest

class TestPutV1MachineDatesIdRequest(unittest.TestCase):
    """PutV1MachineDatesIdRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PutV1MachineDatesIdRequest:
        """Test PutV1MachineDatesIdRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PutV1MachineDatesIdRequest`
        """
        model = PutV1MachineDatesIdRequest()
        if include_optional:
            return PutV1MachineDatesIdRequest(
                time_offset = 56
            )
        else:
            return PutV1MachineDatesIdRequest(
        )
        """

    def testPutV1MachineDatesIdRequest(self):
        """Test PutV1MachineDatesIdRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
