# coding: utf-8

"""
    SleepHQ

    SleepHQ is an online platform for CPAP users to view, share and analyse their data to get the best night's sleep possible. Visit https://sleephq.com for more details.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sleephq.api.imports_api import ImportsApi


class TestImportsApi(unittest.TestCase):
    """ImportsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ImportsApi()

    def tearDown(self) -> None:
        pass

    def test_delete_v1_imports_id(self) -> None:
        """Test case for delete_v1_imports_id

        """
        pass

    def test_get_v1_imports_id(self) -> None:
        """Test case for get_v1_imports_id

        """
        pass

    def test_get_v1_teams_team_id_imports(self) -> None:
        """Test case for get_v1_teams_team_id_imports

        """
        pass

    def test_post_v1_imports_id_process_files(self) -> None:
        """Test case for post_v1_imports_id_process_files

        """
        pass

    def test_post_v1_teams_team_id_imports(self) -> None:
        """Test case for post_v1_teams_team_id_imports

        """
        pass


if __name__ == '__main__':
    unittest.main()
