# coding: utf-8

"""
    SleepHQ

    SleepHQ is an online platform for CPAP users to view, share and analyse their data to get the best night's sleep possible. Visit https://sleephq.com for more details.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sleephq.api.machines_api import MachinesApi


class TestMachinesApi(unittest.TestCase):
    """MachinesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MachinesApi()

    def tearDown(self) -> None:
        pass

    def test_get_v1_machines_id(self) -> None:
        """Test case for get_v1_machines_id

        """
        pass

    def test_get_v1_teams_team_id_machines(self) -> None:
        """Test case for get_v1_teams_team_id_machines

        """
        pass


if __name__ == '__main__':
    unittest.main()
