# coding: utf-8

"""
    SleepHQ

    SleepHQ is an online platform for CPAP users to view, share and analyse their data to get the best night's sleep possible. Visit https://sleephq.com for more details.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sleephq.api.current_user_api import CurrentUserApi


class TestCurrentUserApi(unittest.TestCase):
    """CurrentUserApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CurrentUserApi()

    def tearDown(self) -> None:
        pass

    def test_get_v1_me(self) -> None:
        """Test case for get_v1_me

        """
        pass

    def test_post_v1_me(self) -> None:
        """Test case for post_v1_me

        """
        pass


if __name__ == '__main__':
    unittest.main()
