# coding: utf-8

"""
    SleepHQ

    SleepHQ is an online platform for CPAP users to view, share and analyse their data to get the best night's sleep possible. Visit https://sleephq.com for more details.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sleephq.models.api_v1_team_serializer_list import ApiV1TeamSerializerList

class TestApiV1TeamSerializerList(unittest.TestCase):
    """ApiV1TeamSerializerList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV1TeamSerializerList:
        """Test ApiV1TeamSerializerList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV1TeamSerializerList`
        """
        model = ApiV1TeamSerializerList()
        if include_optional:
            return ApiV1TeamSerializerList(
                data = [
                    {"id":1,"type":"team","attributes":{"id":1662712246,"name":"suscipit","owner_id":3094302479,"time_zone":"rerum","locale":"quas","energy_unit":"id","created_at":"2026-01-14 07:50:46 UTC","updated_at":"2026-01-14 07:50:46 UTC","teams_type":"est"},"relationships":{"machines":{"data":[{"id":1,"type":"machine"}]}}}
                    ]
            )
        else:
            return ApiV1TeamSerializerList(
        )
        """

    def testApiV1TeamSerializerList(self):
        """Test ApiV1TeamSerializerList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
