# coding: utf-8

"""
    SleepHQ

    SleepHQ is an online platform for CPAP users to view, share and analyse their data to get the best night's sleep possible. Visit https://sleephq.com for more details.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sleephq.models.api_v1_device_serializer import ApiV1DeviceSerializer

class TestApiV1DeviceSerializer(unittest.TestCase):
    """ApiV1DeviceSerializer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV1DeviceSerializer:
        """Test ApiV1DeviceSerializer
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV1DeviceSerializer`
        """
        model = ApiV1DeviceSerializer()
        if include_optional:
            return ApiV1DeviceSerializer(
                data = {"id":1,"type":"device","attributes":{"id":8377438313,"name":"nesciunt","brand":"non","device_type":"qui"},"relationships":{}}
            )
        else:
            return ApiV1DeviceSerializer(
        )
        """

    def testApiV1DeviceSerializer(self):
        """Test ApiV1DeviceSerializer"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
