# coding: utf-8

"""
    SleepHQ

    SleepHQ is an online platform for CPAP users to view, share and analyse their data to get the best night's sleep possible. Visit https://sleephq.com for more details.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sleephq.models.api_v1_machine_date_serializer import ApiV1MachineDateSerializer

class TestApiV1MachineDateSerializer(unittest.TestCase):
    """ApiV1MachineDateSerializer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV1MachineDateSerializer:
        """Test ApiV1MachineDateSerializer
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV1MachineDateSerializer`
        """
        model = ApiV1MachineDateSerializer()
        if include_optional:
            return ApiV1MachineDateSerializer(
                data = {"id":1,"type":"machine_date","attributes":{"id":7890282305,"usage":"quisquam","machine_id":5196827045,"date":"2026-01-14","time_offset":5169551805,"created_at":"2026-01-14 07:50:46 UTC","updated_at":"2026-01-14 07:50:46 UTC","large_leak":9639423692,"ahi_summary":"et","pressure_summary":"soluta","leak_rate_summary":"ut","flow_limit_summary":"est","resp_rate_summary":"exercitationem","epap_summary":"labore","machine_settings":"est","pulse_rate_summary":"quae","spo2_summary":"eum","movement_summary":"qui"},"relationships":{}}
            )
        else:
            return ApiV1MachineDateSerializer(
        )
        """

    def testApiV1MachineDateSerializer(self):
        """Test ApiV1MachineDateSerializer"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
