# coding: utf-8

"""
    SleepHQ

    SleepHQ is an online platform for CPAP users to view, share and analyse their data to get the best night's sleep possible. Visit https://sleephq.com for more details.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sleephq.models.api_v1_machine_date_serializer_data_attributes import ApiV1MachineDateSerializerDataAttributes

class TestApiV1MachineDateSerializerDataAttributes(unittest.TestCase):
    """ApiV1MachineDateSerializerDataAttributes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV1MachineDateSerializerDataAttributes:
        """Test ApiV1MachineDateSerializerDataAttributes
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV1MachineDateSerializerDataAttributes`
        """
        model = ApiV1MachineDateSerializerDataAttributes()
        if include_optional:
            return ApiV1MachineDateSerializerDataAttributes(
                id = 56,
                usage = 56,
                machine_id = 56,
                var_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                time_offset = 56,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                large_leak = 56,
                ahi_summary = None,
                pressure_summary = None,
                leak_rate_summary = None,
                flow_limit_summary = None,
                resp_rate_summary = None,
                epap_summary = None,
                machine_settings = None,
                pulse_rate_summary = None,
                spo2_summary = None,
                movement_summary = None
            )
        else:
            return ApiV1MachineDateSerializerDataAttributes(
        )
        """

    def testApiV1MachineDateSerializerDataAttributes(self):
        """Test ApiV1MachineDateSerializerDataAttributes"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
