# coding: utf-8

"""
    SleepHQ

    SleepHQ is an online platform for CPAP users to view, share and analyse their data to get the best night's sleep possible. Visit https://sleephq.com for more details.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sleephq.models.api_v1_import_serializer import ApiV1ImportSerializer

class TestApiV1ImportSerializer(unittest.TestCase):
    """ApiV1ImportSerializer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV1ImportSerializer:
        """Test ApiV1ImportSerializer
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV1ImportSerializer`
        """
        model = ApiV1ImportSerializer()
        if include_optional:
            return ApiV1ImportSerializer(
                data = {"id":1,"type":"import","attributes":{"id":4312389078,"team_id":5973217053,"name":"repudiandae","status":7489284182,"file_size":7273663238,"progress":2670174526,"machine_id":3012790560,"device_id":5423223774,"programatic":true,"failed_reason":"dolorem","created_at":"2026-01-14 07:50:46 UTC","updated_at":"2026-01-14 07:50:46 UTC"},"relationships":{"files":{"data":[{"id":1,"type":"files"}]}}}
            )
        else:
            return ApiV1ImportSerializer(
        )
        """

    def testApiV1ImportSerializer(self):
        """Test ApiV1ImportSerializer"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
