# coding: utf-8

"""
    SleepHQ

    SleepHQ is an online platform for CPAP users to view, share and analyse their data to get the best night's sleep possible. Visit https://sleephq.com for more details.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sleephq.models.api_v1_imports_file_serializer import ApiV1ImportsFileSerializer

class TestApiV1ImportsFileSerializer(unittest.TestCase):
    """ApiV1ImportsFileSerializer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV1ImportsFileSerializer:
        """Test ApiV1ImportsFileSerializer
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV1ImportsFileSerializer`
        """
        model = ApiV1ImportsFileSerializer()
        if include_optional:
            return ApiV1ImportsFileSerializer(
                data = {"id":1,"type":"imports/file","attributes":{"id":5216228666,"added_by_id":1598154568,"added_by_type":"vero","content_hash":"modi","team_id":5135770391,"name":"quibusdam","path":"facere","size":1925836974,"fingerprint_base64":"esse","created_at":"2026-01-14 07:50:46 UTC","updated_at":"2026-01-14 07:50:46 UTC","download_url":"temporibus"},"relationships":{}}
            )
        else:
            return ApiV1ImportsFileSerializer(
        )
        """

    def testApiV1ImportsFileSerializer(self):
        """Test ApiV1ImportsFileSerializer"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
