# coding: utf-8

"""
    SleepHQ

    SleepHQ is an online platform for CPAP users to view, share and analyse their data to get the best night's sleep possible. Visit https://sleephq.com for more details.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sleephq.models.api_v1_user_serializer_data_attributes import ApiV1UserSerializerDataAttributes

class TestApiV1UserSerializerDataAttributes(unittest.TestCase):
    """ApiV1UserSerializerDataAttributes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV1UserSerializerDataAttributes:
        """Test ApiV1UserSerializerDataAttributes
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV1UserSerializerDataAttributes`
        """
        model = ApiV1UserSerializerDataAttributes()
        if include_optional:
            return ApiV1UserSerializerDataAttributes(
                id = 56,
                email = '',
                name = '',
                first_name = '',
                last_name = '',
                time_zone = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return ApiV1UserSerializerDataAttributes(
        )
        """

    def testApiV1UserSerializerDataAttributes(self):
        """Test ApiV1UserSerializerDataAttributes"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
