# coding: utf-8

"""
    SleepHQ

    SleepHQ is an online platform for CPAP users to view, share and analyse their data to get the best night's sleep possible. Visit https://sleephq.com for more details.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sleephq.models.api_v1_user_serializer_data_relationships_teams_data_inner import ApiV1UserSerializerDataRelationshipsTeamsDataInner

class TestApiV1UserSerializerDataRelationshipsTeamsDataInner(unittest.TestCase):
    """ApiV1UserSerializerDataRelationshipsTeamsDataInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV1UserSerializerDataRelationshipsTeamsDataInner:
        """Test ApiV1UserSerializerDataRelationshipsTeamsDataInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV1UserSerializerDataRelationshipsTeamsDataInner`
        """
        model = ApiV1UserSerializerDataRelationshipsTeamsDataInner()
        if include_optional:
            return ApiV1UserSerializerDataRelationshipsTeamsDataInner(
                id = '',
                type = ''
            )
        else:
            return ApiV1UserSerializerDataRelationshipsTeamsDataInner(
        )
        """

    def testApiV1UserSerializerDataRelationshipsTeamsDataInner(self):
        """Test ApiV1UserSerializerDataRelationshipsTeamsDataInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
