# coding: utf-8

"""
    SleepHQ

    SleepHQ is an online platform for CPAP users to view, share and analyse their data to get the best night's sleep possible. Visit https://sleephq.com for more details.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from datetime import date
from pydantic import Field, StrictInt, StrictStr
from typing import Optional
from typing_extensions import Annotated
from sleephq.models.api_v1_journal_serializer import ApiV1JournalSerializer
from sleephq.models.api_v1_journal_serializer_list import ApiV1JournalSerializerList

from sleephq.api_client import ApiClient, RequestSerialized
from sleephq.api_response import ApiResponse
from sleephq.rest import RESTResponseType


class JournalsApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def get_v1_journals_id(
        self,
        id: Annotated[StrictInt, Field(description="Journal ID")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiV1JournalSerializer:
        """get_v1_journals_id

        Retrieve a Journal

        :param id: Journal ID (required)
        :type id: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_v1_journals_id_serialize(
            id=id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ApiV1JournalSerializer",
            '401': None,
            '403': None,
            '404': None,
            '429': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def get_v1_journals_id_with_http_info(
        self,
        id: Annotated[StrictInt, Field(description="Journal ID")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[ApiV1JournalSerializer]:
        """get_v1_journals_id

        Retrieve a Journal

        :param id: Journal ID (required)
        :type id: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_v1_journals_id_serialize(
            id=id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ApiV1JournalSerializer",
            '401': None,
            '403': None,
            '404': None,
            '429': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def get_v1_journals_id_without_preload_content(
        self,
        id: Annotated[StrictInt, Field(description="Journal ID")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """get_v1_journals_id

        Retrieve a Journal

        :param id: Journal ID (required)
        :type id: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_v1_journals_id_serialize(
            id=id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ApiV1JournalSerializer",
            '401': None,
            '403': None,
            '404': None,
            '429': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _get_v1_journals_id_serialize(
        self,
        id,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if id is not None:
            _path_params['id'] = id
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/vnd.api+json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'oauth2'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/v1/journals/{id}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def get_v1_teams_team_id_journals(
        self,
        team_id: Annotated[StrictInt, Field(description="Team ID")],
        page: Annotated[Optional[StrictInt], Field(description="Page of results to fetch.")] = None,
        per_page: Annotated[Optional[StrictInt], Field(description="Number of results to return per page.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiV1JournalSerializerList:
        """get_v1_teams_team_id_journals

        List Journals

        :param team_id: Team ID (required)
        :type team_id: int
        :param page: Page of results to fetch.
        :type page: int
        :param per_page: Number of results to return per page.
        :type per_page: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_v1_teams_team_id_journals_serialize(
            team_id=team_id,
            page=page,
            per_page=per_page,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ApiV1JournalSerializerList",
            '401': None,
            '429': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def get_v1_teams_team_id_journals_with_http_info(
        self,
        team_id: Annotated[StrictInt, Field(description="Team ID")],
        page: Annotated[Optional[StrictInt], Field(description="Page of results to fetch.")] = None,
        per_page: Annotated[Optional[StrictInt], Field(description="Number of results to return per page.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[ApiV1JournalSerializerList]:
        """get_v1_teams_team_id_journals

        List Journals

        :param team_id: Team ID (required)
        :type team_id: int
        :param page: Page of results to fetch.
        :type page: int
        :param per_page: Number of results to return per page.
        :type per_page: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_v1_teams_team_id_journals_serialize(
            team_id=team_id,
            page=page,
            per_page=per_page,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ApiV1JournalSerializerList",
            '401': None,
            '429': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def get_v1_teams_team_id_journals_without_preload_content(
        self,
        team_id: Annotated[StrictInt, Field(description="Team ID")],
        page: Annotated[Optional[StrictInt], Field(description="Page of results to fetch.")] = None,
        per_page: Annotated[Optional[StrictInt], Field(description="Number of results to return per page.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """get_v1_teams_team_id_journals

        List Journals

        :param team_id: Team ID (required)
        :type team_id: int
        :param page: Page of results to fetch.
        :type page: int
        :param per_page: Number of results to return per page.
        :type per_page: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_v1_teams_team_id_journals_serialize(
            team_id=team_id,
            page=page,
            per_page=per_page,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ApiV1JournalSerializerList",
            '401': None,
            '429': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _get_v1_teams_team_id_journals_serialize(
        self,
        team_id,
        page,
        per_page,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if team_id is not None:
            _path_params['team_id'] = team_id
        # process the query parameters
        if page is not None:
            
            _query_params.append(('page', page))
            
        if per_page is not None:
            
            _query_params.append(('per_page', per_page))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/vnd.api+json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'oauth2'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/v1/teams/{team_id}/journals',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def post_v1_teams_team_id_journals(
        self,
        team_id: Annotated[StrictInt, Field(description="Team ID")],
        var_date: Annotated[Optional[date], Field(description="Date")] = None,
        step_count: Annotated[Optional[StrictStr], Field(description="Step Count")] = None,
        weight_grams: Annotated[Optional[StrictInt], Field(description="Weight (Grams)")] = None,
        feeling_score: Annotated[Optional[StrictStr], Field(description="Feeling Score")] = None,
        active_energy_joules: Annotated[Optional[StrictInt], Field(description="Active Energy (Joules)")] = None,
        notes: Annotated[Optional[StrictStr], Field(description="Notes")] = None,
        sleep_stages: Annotated[Optional[StrictStr], Field(description="Sleep Stages")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiV1JournalSerializer:
        """post_v1_teams_team_id_journals

        Add a New Journal

        :param team_id: Team ID (required)
        :type team_id: int
        :param var_date: Date
        :type var_date: date
        :param step_count: Step Count
        :type step_count: str
        :param weight_grams: Weight (Grams)
        :type weight_grams: int
        :param feeling_score: Feeling Score
        :type feeling_score: str
        :param active_energy_joules: Active Energy (Joules)
        :type active_energy_joules: int
        :param notes: Notes
        :type notes: str
        :param sleep_stages: Sleep Stages
        :type sleep_stages: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._post_v1_teams_team_id_journals_serialize(
            team_id=team_id,
            var_date=var_date,
            step_count=step_count,
            weight_grams=weight_grams,
            feeling_score=feeling_score,
            active_energy_joules=active_energy_joules,
            notes=notes,
            sleep_stages=sleep_stages,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '201': "ApiV1JournalSerializer",
            '400': None,
            '401': None,
            '403': None,
            '406': None,
            '422': None,
            '429': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def post_v1_teams_team_id_journals_with_http_info(
        self,
        team_id: Annotated[StrictInt, Field(description="Team ID")],
        var_date: Annotated[Optional[date], Field(description="Date")] = None,
        step_count: Annotated[Optional[StrictStr], Field(description="Step Count")] = None,
        weight_grams: Annotated[Optional[StrictInt], Field(description="Weight (Grams)")] = None,
        feeling_score: Annotated[Optional[StrictStr], Field(description="Feeling Score")] = None,
        active_energy_joules: Annotated[Optional[StrictInt], Field(description="Active Energy (Joules)")] = None,
        notes: Annotated[Optional[StrictStr], Field(description="Notes")] = None,
        sleep_stages: Annotated[Optional[StrictStr], Field(description="Sleep Stages")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[ApiV1JournalSerializer]:
        """post_v1_teams_team_id_journals

        Add a New Journal

        :param team_id: Team ID (required)
        :type team_id: int
        :param var_date: Date
        :type var_date: date
        :param step_count: Step Count
        :type step_count: str
        :param weight_grams: Weight (Grams)
        :type weight_grams: int
        :param feeling_score: Feeling Score
        :type feeling_score: str
        :param active_energy_joules: Active Energy (Joules)
        :type active_energy_joules: int
        :param notes: Notes
        :type notes: str
        :param sleep_stages: Sleep Stages
        :type sleep_stages: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._post_v1_teams_team_id_journals_serialize(
            team_id=team_id,
            var_date=var_date,
            step_count=step_count,
            weight_grams=weight_grams,
            feeling_score=feeling_score,
            active_energy_joules=active_energy_joules,
            notes=notes,
            sleep_stages=sleep_stages,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '201': "ApiV1JournalSerializer",
            '400': None,
            '401': None,
            '403': None,
            '406': None,
            '422': None,
            '429': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def post_v1_teams_team_id_journals_without_preload_content(
        self,
        team_id: Annotated[StrictInt, Field(description="Team ID")],
        var_date: Annotated[Optional[date], Field(description="Date")] = None,
        step_count: Annotated[Optional[StrictStr], Field(description="Step Count")] = None,
        weight_grams: Annotated[Optional[StrictInt], Field(description="Weight (Grams)")] = None,
        feeling_score: Annotated[Optional[StrictStr], Field(description="Feeling Score")] = None,
        active_energy_joules: Annotated[Optional[StrictInt], Field(description="Active Energy (Joules)")] = None,
        notes: Annotated[Optional[StrictStr], Field(description="Notes")] = None,
        sleep_stages: Annotated[Optional[StrictStr], Field(description="Sleep Stages")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """post_v1_teams_team_id_journals

        Add a New Journal

        :param team_id: Team ID (required)
        :type team_id: int
        :param var_date: Date
        :type var_date: date
        :param step_count: Step Count
        :type step_count: str
        :param weight_grams: Weight (Grams)
        :type weight_grams: int
        :param feeling_score: Feeling Score
        :type feeling_score: str
        :param active_energy_joules: Active Energy (Joules)
        :type active_energy_joules: int
        :param notes: Notes
        :type notes: str
        :param sleep_stages: Sleep Stages
        :type sleep_stages: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._post_v1_teams_team_id_journals_serialize(
            team_id=team_id,
            var_date=var_date,
            step_count=step_count,
            weight_grams=weight_grams,
            feeling_score=feeling_score,
            active_energy_joules=active_energy_joules,
            notes=notes,
            sleep_stages=sleep_stages,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '201': "ApiV1JournalSerializer",
            '400': None,
            '401': None,
            '403': None,
            '406': None,
            '422': None,
            '429': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _post_v1_teams_team_id_journals_serialize(
        self,
        team_id,
        var_date,
        step_count,
        weight_grams,
        feeling_score,
        active_energy_joules,
        notes,
        sleep_stages,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if team_id is not None:
            _path_params['team_id'] = team_id
        # process the query parameters
        # process the header parameters
        # process the form parameters
        if var_date is not None:
            _form_params.append(('date', var_date))
        if step_count is not None:
            _form_params.append(('step_count', step_count))
        if weight_grams is not None:
            _form_params.append(('weight_grams', weight_grams))
        if feeling_score is not None:
            _form_params.append(('feeling_score', feeling_score))
        if active_energy_joules is not None:
            _form_params.append(('active_energy_joules', active_energy_joules))
        if notes is not None:
            _form_params.append(('notes', notes))
        if sleep_stages is not None:
            _form_params.append(('sleep_stages', sleep_stages))
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/vnd.api+json'
                ]
            )

        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = (
                self.api_client.select_header_content_type(
                    [
                        'multipart/form-data', 
                        'application/json'
                    ]
                )
            )
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
            'oauth2'
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/v1/teams/{team_id}/journals',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def put_v1_journals_id(
        self,
        id: Annotated[StrictInt, Field(description="Journal ID")],
        var_date: Annotated[Optional[date], Field(description="Date")] = None,
        step_count: Annotated[Optional[StrictStr], Field(description="Step Count")] = None,
        weight_grams: Annotated[Optional[StrictInt], Field(description="Weight (Grams)")] = None,
        feeling_score: Annotated[Optional[StrictStr], Field(description="Feeling Score")] = None,
        active_energy_joules: Annotated[Optional[StrictInt], Field(description="Active Energy (Joules)")] = None,
        notes: Annotated[Optional[StrictStr], Field(description="Notes")] = None,
        sleep_stages: Annotated[Optional[StrictStr], Field(description="Sleep Stages")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiV1JournalSerializer:
        """put_v1_journals_id

        Update a Journal

        :param id: Journal ID (required)
        :type id: int
        :param var_date: Date
        :type var_date: date
        :param step_count: Step Count
        :type step_count: str
        :param weight_grams: Weight (Grams)
        :type weight_grams: int
        :param feeling_score: Feeling Score
        :type feeling_score: str
        :param active_energy_joules: Active Energy (Joules)
        :type active_energy_joules: int
        :param notes: Notes
        :type notes: str
        :param sleep_stages: Sleep Stages
        :type sleep_stages: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._put_v1_journals_id_serialize(
            id=id,
            var_date=var_date,
            step_count=step_count,
            weight_grams=weight_grams,
            feeling_score=feeling_score,
            active_energy_joules=active_energy_joules,
            notes=notes,
            sleep_stages=sleep_stages,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ApiV1JournalSerializer",
            '400': None,
            '401': None,
            '403': None,
            '404': None,
            '406': None,
            '422': None,
            '429': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def put_v1_journals_id_with_http_info(
        self,
        id: Annotated[StrictInt, Field(description="Journal ID")],
        var_date: Annotated[Optional[date], Field(description="Date")] = None,
        step_count: Annotated[Optional[StrictStr], Field(description="Step Count")] = None,
        weight_grams: Annotated[Optional[StrictInt], Field(description="Weight (Grams)")] = None,
        feeling_score: Annotated[Optional[StrictStr], Field(description="Feeling Score")] = None,
        active_energy_joules: Annotated[Optional[StrictInt], Field(description="Active Energy (Joules)")] = None,
        notes: Annotated[Optional[StrictStr], Field(description="Notes")] = None,
        sleep_stages: Annotated[Optional[StrictStr], Field(description="Sleep Stages")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[ApiV1JournalSerializer]:
        """put_v1_journals_id

        Update a Journal

        :param id: Journal ID (required)
        :type id: int
        :param var_date: Date
        :type var_date: date
        :param step_count: Step Count
        :type step_count: str
        :param weight_grams: Weight (Grams)
        :type weight_grams: int
        :param feeling_score: Feeling Score
        :type feeling_score: str
        :param active_energy_joules: Active Energy (Joules)
        :type active_energy_joules: int
        :param notes: Notes
        :type notes: str
        :param sleep_stages: Sleep Stages
        :type sleep_stages: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._put_v1_journals_id_serialize(
            id=id,
            var_date=var_date,
            step_count=step_count,
            weight_grams=weight_grams,
            feeling_score=feeling_score,
            active_energy_joules=active_energy_joules,
            notes=notes,
            sleep_stages=sleep_stages,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ApiV1JournalSerializer",
            '400': None,
            '401': None,
            '403': None,
            '404': None,
            '406': None,
            '422': None,
            '429': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def put_v1_journals_id_without_preload_content(
        self,
        id: Annotated[StrictInt, Field(description="Journal ID")],
        var_date: Annotated[Optional[date], Field(description="Date")] = None,
        step_count: Annotated[Optional[StrictStr], Field(description="Step Count")] = None,
        weight_grams: Annotated[Optional[StrictInt], Field(description="Weight (Grams)")] = None,
        feeling_score: Annotated[Optional[StrictStr], Field(description="Feeling Score")] = None,
        active_energy_joules: Annotated[Optional[StrictInt], Field(description="Active Energy (Joules)")] = None,
        notes: Annotated[Optional[StrictStr], Field(description="Notes")] = None,
        sleep_stages: Annotated[Optional[StrictStr], Field(description="Sleep Stages")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """put_v1_journals_id

        Update a Journal

        :param id: Journal ID (required)
        :type id: int
        :param var_date: Date
        :type var_date: date
        :param step_count: Step Count
        :type step_count: str
        :param weight_grams: Weight (Grams)
        :type weight_grams: int
        :param feeling_score: Feeling Score
        :type feeling_score: str
        :param active_energy_joules: Active Energy (Joules)
        :type active_energy_joules: int
        :param notes: Notes
        :type notes: str
        :param sleep_stages: Sleep Stages
        :type sleep_stages: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._put_v1_journals_id_serialize(
            id=id,
            var_date=var_date,
            step_count=step_count,
            weight_grams=weight_grams,
            feeling_score=feeling_score,
            active_energy_joules=active_energy_joules,
            notes=notes,
            sleep_stages=sleep_stages,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ApiV1JournalSerializer",
            '400': None,
            '401': None,
            '403': None,
            '404': None,
            '406': None,
            '422': None,
            '429': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _put_v1_journals_id_serialize(
        self,
        id,
        var_date,
        step_count,
        weight_grams,
        feeling_score,
        active_energy_joules,
        notes,
        sleep_stages,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if id is not None:
            _path_params['id'] = id
        # process the query parameters
        # process the header parameters
        # process the form parameters
        if var_date is not None:
            _form_params.append(('date', var_date))
        if step_count is not None:
            _form_params.append(('step_count', step_count))
        if weight_grams is not None:
            _form_params.append(('weight_grams', weight_grams))
        if feeling_score is not None:
            _form_params.append(('feeling_score', feeling_score))
        if active_energy_joules is not None:
            _form_params.append(('active_energy_joules', active_energy_joules))
        if notes is not None:
            _form_params.append(('notes', notes))
        if sleep_stages is not None:
            _form_params.append(('sleep_stages', sleep_stages))
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/vnd.api+json'
                ]
            )

        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = (
                self.api_client.select_header_content_type(
                    [
                        'multipart/form-data', 
                        'application/json'
                    ]
                )
            )
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
            'oauth2'
        ]

        return self.api_client.param_serialize(
            method='PUT',
            resource_path='/v1/journals/{id}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


